using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WolcenEditor
{
    public class CharacterData
    {
        public string Name { get; set; }
        public string PlayerId { get; set; }
        public string CharacterId { get; set; }
        public int DifficultyMode { get; set; }
        public int League { get; set; }
        public string UpdatedAt { get; set; }

        public CharacterCustomization CharacterCustomization { get; set; }

        public Stats Stats { get; set; }

        public IList<UnlockedSkill> UnlockedSkills { get; set; }

        public IList<SkillBar> SkillBar { get; set; }

        public IList<string> PassiveSkills { get; set; }

        public IList<BeltConfig> BeltConfig { get; set; }

        public Progression Progression { get; set; }

        public Telemetry Telemetry { get; set; }

        public Versions Versions { get; set; }

        public CharacterCosmeticInventory CharacterCosmeticInventory { get; set; }

        public IList<InventoryEquipped> InventoryEquipped { get; set; }

        public IList<InventoryGrid> InventoryGrid { get; set; }

        public IList<InventoryBelt> InventoryBelt { get; set; }

        public IList<PSTConfig> PSTConfig { get; set; }

        public ApocalypticData ApocalypticData { get; set; }

        public IList<Tutorials> Tutorials { get; set; }

        public IList<Sequences> Sequences { get; set; }

        public LastGameParameters LastGameParameters { get; set; }

    }

    public static class CharacterIO
    {
        public static CharacterData ReadCharacter(string filePath)
        {
            string jsonData = File.ReadAllText(filePath);

            CharacterData character = JsonConvert.DeserializeObject<CharacterData>(jsonData);
            return character;
        }

        public static void WriteCharacter(string outputPath, CharacterData characterData)
        {
            if (File.Exists($"{outputPath}") && !File.Exists($"{outputPath}.bak"))
            {
                string oldJsonFile = File.ReadAllText(outputPath);
                File.WriteAllText($"{outputPath}.bak", oldJsonFile);
            }
            string newJsonFile = JsonConvert.SerializeObject(characterData, Formatting.Indented);
            File.WriteAllText(outputPath, newJsonFile);
        }
    }

    public static class WolcenStaticData
    {
        public static readonly Dictionary<string, List<int>> QuestSelections = new Dictionary<string, List<int>>
        {
            { "INTRO_Quest1", new List<int> { 1} },

            { "ACT1_Quest1", new List<int> { 1 } },
            { "ACT1_Quest2", new List<int> { 1, 2, 3, 7, 10, 12, 13, 14 } },
            { "ACT1_Quest3", new List<int> { 1,3,5,6,8,9,12} },
            { "ACT1_Quest4", new List<int> { 1,3,5,6,7,9,11 } },
            { "ACT1_Quest5", new List<int> { 1,2,3,4,5,6,7,8,10 } },

            { "ACT2_Quest1", new List<int> { 1,3 } },
            { "ACT2_Quest2", new List<int> { 1,2,3,4 } },
            { "ACT2_Quest3", new List<int> { 1,2,5 } },
            { "ACT2_Quest4", new List<int> { 1,2,3,4 } },
            { "ACT2_Quest5", new List<int> { 1,2,3,4,5,6,7,9,10 } },
            { "ACT2_Quest6", new List<int> { 1,3,4,5,6,7,8 } },

            { "ACT3_Quest1", new List<int> { 1,2,3,4,6,7,8 } },
            { "ACT3_Quest2", new List<int> { 1,3,5,7 } },
            { "ACT3_Quest3", new List<int> { 1,3,4,5,7 } },
            { "ACT3_Quest4", new List<int> { 1,2,4,5,6,8 } },
        };

        public static readonly Dictionary<int, string> Gender = new Dictionary<int, string>
        {
            {0, "Male" },
            {1, "Female" }
        };

        public static readonly Dictionary<int, string> HairColorBank = new Dictionary<int, string>
        {
            {1, "#3B2215" },
            {2, "#5B391F" },
            {3, "#120E0B" },
            {4, "#965F35" },
            {5, "#684D41" },
            {6, "#FC9432" },
            {7, "#824C1A" },
            {8, "#FCFCFC" },
            {9, "#828282" },
            {51, "#424242" },
            {10, "#DBAC73" },
            {11, "#FCCA32" },
            {12, "#FCD96F" },
            {13, "#FFD9AE" },
            {14, "#FC603D" },
            {15, "#82311F" },
            {16, "#2E110B" },
            {17, "#F46816" },
            {18, "#863505" },
            {19, "#9C5927" },
            {50, "#FF8000" },
            {20, "#822424" },
            {22, "#970A05" },
            {23, "#410402" },
            {24, "#FE1111" },
            {26, "#35B3FC" },
            {27, "#1B5C82" },
            {28, "#4454FC" },
            {29, "#232B82" },
            {30, "#0C0F2E" },
            {31, "#C244FC" },
            {32, "#642382" },
            {34, "#822F73" },
            {35, "#2E1129" },
            {36, "#FF399F" },
            {37, "#FBB1E2" },
            {38, "#71054D" },
            {39, "#FF399F" },
            {40, "#35FC49" },
            {41, "#FF399F" },
        };

        public static readonly Dictionary<int, string> Sexes = new Dictionary<int, string>
        {
            {0, "Male" },
            {1, "Female" },

        };

        public static readonly Dictionary<int, string> EyeColor = new Dictionary<int, string>
        {
            {1, "1.png" },
            {2, "2.png" },
            {3, "3.png" },
            {4, "4.png" },
            {5, "5.png" },
            {6, "6.png" },
            {7, "7.png" },
            {8, "8.png" },
            {9, "9.png" },
            {10, "10.png" },
            {11, "11.png" },
            {12, "12.png" },
            {13, "13.png" }
        };

        public static readonly Dictionary<int, string> Face = new Dictionary<int, string>
        {
            {1, "Head_male_01.png" },
            {2, "Head_male_02.png" },
            {3, "Head_male_03.png" },
            {4, "Head_male_04.png" },
            {5, "Head_female_01.png" },
            {6, "Head_female_02.png" },
            {7, "Head_female_03.png" },
            {8, "Head_female_04.png" }
        };

        public static readonly Dictionary<int, string> Beard = new Dictionary<int, string>
        {
            {1, "1.png" },
            {2, "2.png" },
            {3, "3.png" },
            {4, "4.png" },
            {5, "5.png" },
            {6, "6.png" },
            {7, "7.png" },
            {8, "8.png" },
            {9, "9.png" }
        };

        public static readonly Dictionary<int, string> HairStyle = new Dictionary<int, string>
        {
            {1, "1.png" },
            {2, "2.png" },
            {3, "3.png" },
            {4, "4.png" },
            {5, "5.png" },
            {6, "6.png" },
            {100, "100.png" },
            {101, "101.png" },
            {102, "102.png" },
            {103, "103.png" },
            {104, "104.png" },
            {105, "105.png" },
            {106, "106.png" },
            {107, "107.png" },
            {108, "108.png" },
            {109, "109.png" },
            {110, "110.png" }
        };

        public static readonly Dictionary<int, string> SkinColor = new Dictionary<int, string>
        {
            { 100, "#d8c3a8" },
            { 101, "#a9877d" },
            { 102, "#9c7767" },
            { 103, "#795e4f" },
            { 104, "#64483a" },
            { 105, "#533c36" },
            { 106, "#2c2a25" },
            { 107, "#896f56" },
            { 108, "#856858" },
            { 109, "#847878" },
            { 110, "#807461" },
            { 111, "#181412" },
            { 200, "#d8c3a8" },
            { 201, "#a9877d" },
            { 202, "#9c7767" },
            { 203, "#795e4f" },
            { 204, "#64483a" },
            { 205, "#533c36" },
            { 206, "#2c2a25" },
            { 207, "#896f56" },
            { 208, "#856858" },
            { 209, "#847878" },
            { 210, "#807461" },
            { 211, "#181412" },
            { 300, "#d8c3a8" },
            { 301, "#a9877d" },
            { 302, "#9c7767" },
            { 303, "#795e4f" },
            { 304, "#64483a" },
            { 305, "#533c36" },
            { 306, "#2c2a25" },
            { 307, "#896f56" },
            { 308, "#856858" },
            { 309, "#847878" },
            { 310, "#807461" },
            { 311, "#181412" },
            { 400, "#d8c3a8" },
            { 401, "#a9877d" },
            { 402, "#9c7767" },
            { 403, "#795e4f" },
            { 404, "#64483a" },
            { 405, "#533c36" },
            { 406, "#2c2a25" },
            { 407, "#896f56" },
            { 408, "#856858" },
            { 409, "#847878" },
            { 410, "#807461" },
            { 411, "#181412" },
            { 512, "#F7DFC1" },
            { 500, "#d8c3a8" },
            { 501, "#a9877d" },
            { 502, "#9c7767" },
            { 503, "#795e4f" },
            { 504, "#64483a" },
            { 505, "#533c36" },
            { 506, "#2c2a25" },
            { 507, "#896f56" },
            { 508, "#856858" },
            { 509, "#847878" },
            { 510, "#807461" },
            { 511, "#181412" },
            { 612, "#F7DFC1" },
            { 600, "#d8c3a8" },
            { 601, "#a9877d" },
            { 602, "#9c7767" },
            { 603, "#795e4f" },
            { 604, "#64483a" },
            { 605, "#533c36" },
            { 606, "#2c2a25" },
            { 607, "#896f56" },
            { 608, "#856858" },
            { 609, "#847878" },
            { 610, "#807461" },
            { 611, "#181412" },
            { 712, "#F7DFC1" },
            { 700, "#d8c3a8" },
            { 701, "#a9877d" },
            { 702, "#9c7767" },
            { 703, "#795e4f" },
            { 704, "#64483a" },
            { 705, "#533c36" },
            { 706, "#2c2a25" },
            { 707, "#896f56" },
            { 708, "#856858" },
            { 709, "#847878" },
            { 710, "#807461" },
            { 711, "#181412" },
            { 812, "#F7DFC1" },
            { 800, "#d8c3a8" },
            { 801, "#a9877d" },
            { 802, "#9c7767" },
            { 803, "#795e4f" },
            { 804, "#64483a" },
            { 805, "#533c36" },
            { 806, "#2c2a25" },
            { 807, "#896f56" },
            { 808, "#856858" },
            { 809, "#847878" },
            { 810, "#807461" },
            { 811, "#181412" }
        };

        public static readonly Dictionary<string, string> ItemAccessories = new Dictionary<string, string>
        {
            { "Alchemist_Sash", "belt_alchemist.png" },
            { "Heavy_Belt", "belt_warrior.png" },
            { "Assassin_Waistband", "belt_assassin.png" },
            { "Gladiator_Belt", "belt_gladiator.png" },
            { "Templar_Waistband", "belt_warlock.png" },
            { "Belt_Gold", "Belt_tier11.png" },
            { "Belt_Silver", "Belt_tier04.png" },
            { "Belt_Platine", "Belt_tier09.png" },
            { "Topaz_Ring", "ring_attributes_yellow_tier1.png" },
            { "Aquamarine_Ring", "ring_attributes_cyan_tier1.png" },
            { "Sapphire_Ring", "ring_attributes_blue_tier1.png" },
            { "Emerald_Ring", "ring_attributes_green_tier1.png" },
            { "Ruby_Ring", "ring_attributes_red_tier1.png" },
            { "Bloodstar_Ring", "ring_jewel.png" },
            { "Steel_Ring", "ring_marksman.png" },
            { "Ring_Gold", "Ring_tier11.png" },
            { "Ring_Silver", "Ring_tier04.png" },
            { "Ring_Platine", "Ring_tier09.png" },
            { "Amethyst_Amulet", "amulet_4.png" },
            { "Ruby_Amulet", "amulet_2.png" },
            { "Goldstone_Amulet", "amulet_3.png" },
            { "Emerald_Amulet", "amulet_7.png" },
            { "Omnistar_Amulet", "amulet_1.png" },
            { "Amulet_Gold", "amulet_tier11.png" },
            { "Amulet_Silver", "amulet_tier04.png" },
            { "Amulet_Platine", "amulet_tier09.png" },
            { "Alchemist_Sash_1", "belt_alchemist.png" },
            { "Heavy_Belt_1", "belt_warrior.png" },
            { "Assassin_Waistband_1", "belt_assassin.png" },
            { "Gladiator_Belt_1", "belt_gladiator.png" },
            { "Templar_Waistband_1", "belt_warlock.png" },
            { "Belt_Gold_1", "Belt_tier11.png" },
            { "Belt_Silver_1", "Belt_tier04.png" },
            { "Belt_Platine_1", "Belt_tier09.png" },
            { "Topaz_Ring_1", "ring_attributes_yellow_tier1.png" },
            { "Aquamarine_Ring_1", "ring_attributes_cyan_tier1.png" },
            { "Sapphire_Ring_1", "ring_attributes_blue_tier1.png" },
            { "Emerald_Ring_1", "ring_attributes_green_tier1.png" },
            { "Ruby_Ring_1", "ring_attributes_red_tier1.png" },
            { "Bloodstar_Ring_1", "ring_jewel.png" },
            { "Steel_Ring_1", "ring_marksman.png" },
            { "Ring_Gold_1", "Ring_tier11.png" },
            { "Ring_Silver_1", "Ring_tier04.png" },
            { "Ring_Platine_1", "Ring_tier09.png" },
            { "Amethyst_Amulet_1", "amulet_4.png" },
            { "Ruby_Amulet_1", "amulet_2.png" },
            { "Goldstone_Amulet_1", "amulet_3.png" },
            { "Emerald_Amulet_1", "amulet_7.png" },
            { "Omnistar_Amulet_1", "amulet_1.png" },
            { "Amulet_Gold_1", "amulet_tier11.png" },
            { "Amulet_Silver_1", "amulet_tier04.png" },
            { "Amulet_Platine_1", "amulet_tier09.png" },
            { "Alchemist_Sash_2", "belt_alchemist.png" },
            { "Heavy_Belt_2", "belt_warrior.png" },
            { "Assassin_Waistband_2", "belt_assassin.png" },
            { "Gladiator_Belt_2", "belt_gladiator.png" },
            { "Templar_Waistband_2", "belt_warlock.png" },
            { "Belt_Gold_2", "Belt_tier11.png" },
            { "Belt_Silver_2", "Belt_tier04.png" },
            { "Belt_Platine_2", "Belt_tier09.png" },
            { "Topaz_Ring_2", "ring_attributes_yellow_tier1.png" },
            { "Aquamarine_Ring_2", "ring_attributes_cyan_tier1.png" },
            { "Sapphire_Ring_2", "ring_attributes_blue_tier1.png" },
            { "Emerald_Ring_2", "ring_attributes_green_tier1.png" },
            { "Ruby_Ring_2", "ring_attributes_red_tier1.png" },
            { "Bloodstar_Ring_2", "ring_jewel.png" },
            { "Steel_Ring_2", "ring_marksman.png" },
            { "Ring_Gold_2", "Ring_tier11.png" },
            { "Ring_Silver_2", "Ring_tier04.png" },
            { "Ring_Platine_2", "Ring_tier09.png" },
            { "Amethyst_Amulet_2", "amulet_4.png" },
            { "Ruby_Amulet_2", "amulet_2.png" },
            { "Goldstone_Amulet_2", "amulet_3.png" },
            { "Emerald_Amulet_2", "amulet_7.png" },
            { "Omnistar_Amulet_2", "amulet_1.png" },
            { "Amulet_Gold_2", "amulet_tier11.png" },
            { "Amulet_Silver_2", "amulet_tier04.png" },
            { "Amulet_Platine_2", "amulet_tier09.png" },
            { "Alchemist_Sash_3", "belt_alchemist.png" },
            { "Heavy_Belt_3", "belt_warrior.png" },
            { "Assassin_Waistband_3", "belt_assassin.png" },
            { "Gladiator_Belt_3", "belt_gladiator.png" },
            { "Templar_Waistband_3", "belt_warlock.png" },
            { "Belt_Gold_3", "Belt_tier11.png" },
            { "Belt_Silver_3", "Belt_tier04.png" },
            { "Belt_Platine_3", "Belt_tier09.png" },
            { "Topaz_Ring_3", "ring_attributes_yellow_tier1.png" },
            { "Aquamarine_Ring_3", "ring_attributes_cyan_tier1.png" },
            { "Sapphire_Ring_3", "ring_attributes_blue_tier1.png" },
            { "Emerald_Ring_3", "ring_attributes_green_tier1.png" },
            { "Ruby_Ring_3", "ring_attributes_red_tier1.png" },
            { "Bloodstar_Ring_3", "ring_jewel.png" },
            { "Steel_Ring_3", "ring_marksman.png" },
            { "Ring_Gold_3", "Ring_tier11.png" },
            { "Ring_Silver_3", "Ring_tier04.png" },
            { "Ring_Platine_3", "Ring_tier09.png" },
            { "Amethyst_Amulet_3", "amulet_4.png" },
            { "Ruby_Amulet_3", "amulet_2.png" },
            { "Goldstone_Amulet_3", "amulet_3.png" },
            { "Emerald_Amulet_3", "amulet_7.png" },
            { "Omnistar_Amulet_3", "amulet_1.png" },
            { "Amulet_Gold_3", "amulet_tier11.png" },
            { "Amulet_Silver_3", "amulet_tier04.png" },
            { "Amulet_Platine_3", "amulet_tier09.png" },
            { "Alchemist_Sash_4", "belt_alchemist.png" },
            { "Heavy_Belt_4", "belt_warrior.png" },
            { "Assassin_Waistband_4", "belt_assassin.png" },
            { "Gladiator_Belt_4", "belt_gladiator.png" },
            { "Templar_Waistband_4", "belt_warlock.png" },
            { "Belt_Gold_4", "Belt_tier11.png" },
            { "Belt_Silver_4", "Belt_tier04.png" },
            { "Belt_Platine_4", "Belt_tier09.png" },
            { "Topaz_Ring_4", "ring_attributes_yellow_tier1.png" },
            { "Aquamarine_Ring_4", "ring_attributes_cyan_tier1.png" },
            { "Sapphire_Ring_4", "ring_attributes_blue_tier1.png" },
            { "Emerald_Ring_4", "ring_attributes_green_tier1.png" },
            { "Ruby_Ring_4", "ring_attributes_red_tier1.png" },
            { "Bloodstar_Ring_4", "ring_jewel.png" },
            { "Steel_Ring_4", "ring_marksman.png" },
            { "Ring_Gold_4", "Ring_tier11.png" },
            { "Ring_Silver_4", "Ring_tier04.png" },
            { "Ring_Platine_4", "Ring_tier09.png" },
            { "Amethyst_Amulet_4", "amulet_4.png" },
            { "Ruby_Amulet_4", "amulet_2.png" },
            { "Goldstone_Amulet_4", "amulet_3.png" },
            { "Emerald_Amulet_4", "amulet_7.png" },
            { "Omnistar_Amulet_4", "amulet_1.png" },
            { "Amulet_Gold_4", "amulet_tier11.png" },
            { "Amulet_Silver_4", "amulet_tier04.png" },
            { "Amulet_Platine_4", "amulet_tier09.png" },
            { "Omnistar_Amulet_Reward", "amulet_1.png" },
            { "Topaz_Ring_Reward", "ring_attributes_yellow_tier1.png" },
            { "Aquamarine_Ring_Reward", "ring_attributes_cyan_tier1.png" },
            { "Sapphire_Ring_Reward", "ring_attributes_blue_tier1.png" },
            { "Ruby_Ring_Reward", "ring_attributes_red_tier1.png" }
        };

        public static readonly Dictionary<string, string> ItemWeapon = new Dictionary<string, string>
        {
            { "1h_shield_tier1", "h1_shield_tier1.png" },
            { "1h_shield_tier2", "h1_shield_tier2.png" },
            { "1h_shield_tier3", "h1_shield_tier3.png" },
            { "1h_shield_tier4", "h1_shield_tier4.png" },
            { "1h_shield_tier5", "h1_shield_tier5.png" },
            { "1h_shield_tier6", "h1_shield_tier6.png" },
            { "1h_shield_tier7", "h1_shield_tier7.png" },
            { "1h_shield_tier8", "h1_shield_tier8.png" },
            { "1h_shield_tier9", "h1_shield_tier9.png" },
            { "1h_shield_tier10", "h1_shield_tier10.png" },
            { "1h_shield_tier11", "h1_shield_tier11.png" },
            { "1h_shield_tier12", "h1_shield_tier12.png" },
            { "1h_shield_tier13", "h1_shield_tier13.png" },
            { "1h_shield_tier14", "h1_shield_tier14.png" },
            { "1h_shield_tier15", "h1_shield_tier15.png" },
            { "1h_shield_tier16", "h1_shield_tier16.png" },
            { "1h_shield_tier17", "h1_shield_tier17.png" },
            { "1h_shield_tier18", "h1_shield_tier18.png" },
            { "1h_shield_tier3_Reward", "h1_shield_tier3.png" },
            { "unique_shield_sacred", "h1_shield_quintet_of_sundowns.png" },
            { "unique_shield_thing", "1h_shield_the_thing.png" },
            { "unique_shield_shadow", "1h_shield_in_tenebris_gloriam.png" },
            { "unique_intro_shield", "1h_shield_in_tenebris_gloriam.png" },
            { "Unique_bow_projectile", "bow_2h_templar.png" },
            { "Unique_fire_Sword", "Doomslayer.png" },
            { "Unique_stasis_staff", "lantern_staff.png" },
            { "Unique_rend_dagger", "corrupted_dagger.png" },
            { "Unique_2h_axe", "h2_axe_orc.png" },
            { "Unique_poison_dagger", "1h_dagger_senates_imperatum.png" },
            { "Unique_lightning_staff", "h2_staff_zapstick.png" },
            { "Unique_stone_sword", "2h_sword_rigards_hope.png" },
            { "Unique_vanity_Sword", "h1_sword_vanitys_edge.png" },
            { "Unique_envy_Sword", "h1_sword_blade_of_envy.png" },
            { "unique_cc_mace", "h1_hammer_orc.png" },
            { "Unique_1h_axe", "1h_axe_the_apex.png" },
            { "Unique_lightning_sword", "2h_sword_zephyron_herald_of_change.png" },
            { "Unique_gun_pierce", "1h_pistol_grahams_shipkiller.png" },
            { "Unique_purifier_catalyst", "1h_purifier_catalyst.png" },
            { "unique_mace_sleeper", "h2_hammer_hand_of_the_sleeper.png" },
            { "unique_flintlock_gun", "h1_pistol_FlintLockPistol.png" },
            { "unique_spellblade_catalyst", "h1_offhand_spellbladecatalyst.png" },
            { "Unique_intro_sword", "1h_sword_republic.png" },
            { "1H_Sword_Starter", "h1_sword_tier1.png" },
            { "2H_Staff_Starter", "h2_staff_tier1.png" },
            { "2H_Bow_Starter", "h2_bow_tier1.png" },
            { "Unique_dominion_staff", "h2_staff_zapstick.png" },
            { "Unique_driftwood_bow", "bow_2h_templar.png" },
            { "unique_shadow_catalyst", "h1_offhand_spellbladecatalyst.png" },
            { "Unique_delivrance_axe", "h2_axe_orc.png" },
            { "unique_shield_sacred_max", "h1_shield_quintet_of_sundowns.png" },
            { "unique_shield_thing_max", "1h_shield_the_thing.png" },
            { "unique_shield_shadow_max", "1h_shield_in_tenebris_gloriam.png" },
            { "Unique_bow_projectile_max", "bow_2h_templar.png" },
            { "Unique_fire_Sword_max", "Doomslayer.png" },
            { "Unique_stasis_staff_max", "lantern_staff.png" },
            { "Unique_rend_dagger_max", "corrupted_dagger.png" },
            { "Unique_2h_axe_max", "h2_axe_orc.png" },
            { "Unique_poison_dagger_max", "1h_dagger_senates_imperatum.png" },
            { "Unique_lightning_staff_max", "h2_staff_zapstick.png" },
            { "Unique_stone_sword_max", "2h_sword_rigards_hope.png" },
            { "Unique_vanity_Sword_max", "h1_sword_vanitys_edge.png" },
            { "Unique_envy_Sword_max", "h1_sword_blade_of_envy.png" },
            { "unique_cc_mace_max", "h1_hammer_orc.png" },
            { "Unique_1h_axe_max", "1h_axe_the_apex.png" },
            { "Unique_lightning_sword_max", "2h_sword_zephyron_herald_of_change.png" },
            { "Unique_gun_pierce_max", "1h_pistol_grahams_shipkiller.png" },
            { "unique_mace_sleeper_max", "h2_hammer_hand_of_the_sleeper.png" },
            { "1H_Axe_Tier1", "h1_axe_tier1.png" },
            { "1H_Dagger_Tier1", "h1_dagger_tier1.png" },
            { "1H_Hammer_Tier1", "h1_Hammer_tier1.png" },
            { "1H_OffHand_Tier1", "h1_offhand_tier1.png" },
            { "1h_pistol_tier1", "h1_pistol_tier1.png" },
            { "1H_Sword_Tier1", "h1_sword_tier1.png" },
            { "2H_Axe_Tier1", "h2_axe_tier1.png" },
            { "2H_Bow_Tier1", "h2_bow_tier1.png" },
            { "2H_Hammer_Tier1", "h2_hammer_tier1.png" },
            { "2H_Staff_Tier1", "h2_staff_tier1.png" },
            { "2H_Sword_Tier1", "h2_sword_tier1.png" },
            { "1H_Axe_Tier2", "h1_axe_tier2.png" },
            { "1H_Dagger_Tier2", "h1_dagger_tier2.png" },
            { "1H_Hammer_Tier2", "h1_Hammer_tier2.png" },
            { "1H_OffHand_Tier2", "h1_offhand_tier2.png" },
            { "1h_pistol_tier2", "h1_pistol_tier2.png" },
            { "1H_Sword_Tier2", "h1_sword_tier2.png" },
            { "2H_Axe_Tier2", "h2_axe_tier2.png" },
            { "2H_Bow_Tier2", "h2_bow_tier2.png" },
            { "2H_Hammer_Tier2", "h2_hammer_tier2.png" },
            { "2H_Staff_Tier2", "h2_staff_tier2.png" },
            { "2H_Sword_Tier2", "h2_sword_tier2.png" },
            { "1H_Axe_Tier3", "h1_axe_tier3.png" },
            { "1H_Dagger_Tier3", "h1_dagger_tier3.png" },
            { "1H_Hammer_Tier3", "h1_Hammer_tier3.png" },
            { "1H_OffHand_Tier3", "h1_offhand_tier3.png" },
            { "1h_pistol_tier3", "h1_pistol_tier3.png" },
            { "1H_Sword_Tier3", "h1_sword_tier3.png" },
            { "2H_Axe_Tier3", "h2_axe_tier3.png" },
            { "2H_Bow_Tier3", "h2_bow_tier3.png" },
            { "2H_Hammer_Tier3", "h2_hammer_tier3.png" },
            { "2H_Staff_Tier3", "h2_staff_tier3.png" },
            { "2H_Sword_Tier3", "h2_sword_tier3.png" },
            { "1H_Axe_Tier4", "h1_axe_tier4.png" },
            { "1H_Dagger_Tier4", "h1_dagger_tier4.png" },
            { "1H_Hammer_Tier4", "h1_Hammer_tier4.png" },
            { "1H_OffHand_Tier4", "h1_offhand_tier4.png" },
            { "1h_pistol_tier4", "h1_pistol_tier4.png" },
            { "1H_Sword_Tier4", "h1_sword_tier4.png" },
            { "2H_Axe_Tier4", "h2_axe_tier4.png" },
            { "2H_Bow_Tier4", "h2_bow_tier4.png" },
            { "2H_Hammer_Tier4", "h2_hammer_tier4.png" },
            { "2H_Staff_Tier4", "h2_staff_tier4.png" },
            { "2H_Sword_Tier4", "h2_sword_tier4.png" },
            { "1H_Axe_Tier5", "h1_axe_tier5.png" },
            { "1H_Dagger_Tier5", "h1_dagger_tier5.png" },
            { "1H_Hammer_Tier5", "h1_Hammer_tier5.png" },
            { "1H_OffHand_Tier5", "h1_offhand_tier5.png" },
            { "1h_pistol_tier5", "h1_pistol_tier5.png" },
            { "1H_Sword_Tier5", "h1_sword_tier5.png" },
            { "2H_Axe_Tier5", "h2_axe_tier5.png" },
            { "2H_Bow_Tier5", "h2_bow_tier5.png" },
            { "2H_Hammer_Tier5", "h2_hammer_tier5.png" },
            { "2H_Staff_Tier5", "h2_staff_tier5.png" },
            { "2H_Sword_Tier5", "h2_sword_tier5.png" },
            { "1H_Axe_Tier6", "h1_axe_tier6.png" },
            { "1H_Dagger_Tier6", "h1_dagger_tier6.png" },
            { "1H_Hammer_Tier6", "h1_Hammer_tier6.png" },
            { "1H_OffHand_Tier6", "h1_offhand_tier6.png" },
            { "1h_pistol_tier6", "h1_pistol_tier6.png" },
            { "1H_Sword_Tier6", "h1_sword_tier6.png" },
            { "2H_Axe_Tier6", "h2_axe_tier6.png" },
            { "2H_Bow_Tier6", "h2_bow_tier6.png" },
            { "2H_Hammer_Tier6", "h2_hammer_tier6.png" },
            { "2H_Staff_Tier6", "h2_staff_tier6.png" },
            { "2H_Sword_Tier6", "h2_sword_tier6.png" },
            { "1H_Axe_Tier7", "h1_axe_tier7.png" },
            { "1H_Dagger_Tier7", "h1_dagger_tier7.png" },
            { "1H_Hammer_Tier7", "h1_Hammer_tier7.png" },
            { "1H_OffHand_Tier7", "h1_offhand_tier7.png" },
            { "1h_pistol_tier7", "h1_pistol_tier7.png" },
            { "1H_Sword_Tier7", "h1_sword_tier7.png" },
            { "2H_Axe_Tier7", "h2_axe_tier7.png" },
            { "2H_Bow_Tier7", "h2_bow_tier7.png" },
            { "2H_Hammer_Tier7", "h2_hammer_tier7.png" },
            { "2H_Staff_Tier7", "h2_staff_tier7.png" },
            { "2H_Sword_Tier7", "h2_sword_tier7.png" },
            { "1H_Axe_Tier8", "h1_axe_tier8.png" },
            { "1H_Dagger_Tier8", "h1_dagger_tier8.png" },
            { "1H_Hammer_Tier8", "h1_Hammer_tier8.png" },
            { "1H_OffHand_Tier8", "h1_offhand_tier8.png" },
            { "1h_pistol_tier8", "h1_pistol_tier8.png" },
            { "1H_Sword_Tier8", "h1_sword_tier8.png" },
            { "2H_Axe_Tier8", "h2_axe_tier8.png" },
            { "2H_Bow_Tier8", "h2_bow_tier8.png" },
            { "2H_Hammer_Tier8", "h2_hammer_tier8.png" },
            { "2H_Staff_Tier8", "h2_staff_tier8.png" },
            { "2H_Sword_Tier8", "h2_sword_tier8.png" },
            { "1H_Axe_Tier9", "h1_axe_tier9.png" },
            { "1H_Dagger_Tier9", "h1_dagger_tier9.png" },
            { "1H_Hammer_Tier9", "h1_Hammer_tier9.png" },
            { "1H_OffHand_Tier9", "h1_offhand_tier9.png" },
            { "1h_pistol_tier9", "h1_pistol_tier9.png" },
            { "1H_Sword_Tier9", "h1_sword_tier9.png" },
            { "2H_Axe_Tier9", "h2_axe_tier9.png" },
            { "2H_Bow_Tier9", "h2_bow_tier9.png" },
            { "2H_Hammer_Tier9", "h2_hammer_tier9.png" },
            { "2H_Staff_Tier9", "h2_staff_tier9.png" },
            { "2H_Sword_Tier9", "h2_sword_tier9.png" },
            { "1H_Axe_Tier10", "h1_axe_tier10.png" },
            { "1H_Dagger_Tier10", "h1_dagger_tier10.png" },
            { "1H_Hammer_Tier10", "h1_Hammer_tier10.png" },
            { "1H_OffHand_Tier10", "h1_offhand_tier10.png" },
            { "1h_pistol_tier10", "h1_pistol_tier10.png" },
            { "1H_Sword_Tier10", "h1_sword_tier10.png" },
            { "2H_Axe_Tier10", "h2_axe_tier10.png" },
            { "2H_Bow_Tier10", "h2_bow_tier10.png" },
            { "2H_Hammer_Tier10", "h2_hammer_tier10.png" },
            { "2H_Staff_Tier10", "h2_staff_tier10.png" },
            { "2H_Sword_Tier10", "h2_sword_tier10.png" },
            { "1H_Axe_Tier11", "h1_axe_tier11.png" },
            { "1H_Dagger_Tier11", "h1_dagger_tier11.png" },
            { "1H_Hammer_Tier11", "h1_Hammer_tier11.png" },
            { "1H_OffHand_Tier11", "h1_offhand_tier11.png" },
            { "1h_pistol_tier11", "h1_pistol_tier11.png" },
            { "1H_Sword_Tier11", "h1_sword_tier11.png" },
            { "2H_Axe_Tier11", "h2_axe_tier11.png" },
            { "2H_Bow_Tier11", "h2_bow_tier11.png" },
            { "2H_Hammer_Tier11", "h2_hammer_tier11.png" },
            { "2H_Staff_Tier11", "h2_staff_tier11.png" },
            { "2H_Sword_Tier11", "h2_sword_tier11.png" },
            { "1H_Axe_Tier12", "h1_axe_tier12.png" },
            { "1H_Dagger_Tier12", "h1_dagger_tier12.png" },
            { "1H_Hammer_Tier12", "h1_Hammer_tier12.png" },
            { "1H_OffHand_Tier12", "h1_offhand_tier12.png" },
            { "1h_pistol_tier12", "h1_pistol_tier12.png" },
            { "1H_Sword_Tier12", "h1_sword_tier12.png" },
            { "2H_Axe_Tier12", "h2_axe_tier12.png" },
            { "2H_Bow_Tier12", "h2_bow_tier12.png" },
            { "2H_Hammer_Tier12", "h2_hammer_tier12.png" },
            { "2H_Staff_Tier12", "h2_staff_tier12.png" },
            { "2H_Sword_Tier12", "h2_sword_tier12.png" },
            { "1H_Axe_Tier13", "h1_axe_tier13.png" },
            { "1H_Dagger_Tier13", "h1_dagger_tier13.png" },
            { "1H_Hammer_Tier13", "h1_Hammer_tier13.png" },
            { "1H_OffHand_Tier13", "h1_offhand_tier13.png" },
            { "1h_pistol_tier13", "h1_pistol_tier13.png" },
            { "1H_Sword_Tier13", "h1_sword_tier13.png" },
            { "2H_Axe_Tier13", "h2_axe_tier13.png" },
            { "2H_Bow_Tier13", "h2_bow_tier13.png" },
            { "2H_Hammer_Tier13", "h2_hammer_tier13.png" },
            { "2H_Staff_Tier13", "h2_staff_tier13.png" },
            { "2H_Sword_Tier13", "h2_sword_tier13.png" },
            { "1H_Axe_Tier14", "h1_axe_tier14.png" },
            { "1H_Dagger_Tier14", "h1_dagger_tier14.png" },
            { "1H_Hammer_Tier14", "h1_Hammer_tier14.png" },
            { "1H_OffHand_Tier14", "h1_offhand_tier14.png" },
            { "1h_pistol_tier14", "h1_pistol_tier14.png" },
            { "1H_Sword_Tier14", "h1_sword_tier14.png" },
            { "2H_Axe_Tier14", "h2_axe_tier14.png" },
            { "2H_Bow_Tier14", "h2_bow_tier14.png" },
            { "2H_Hammer_Tier14", "h2_hammer_tier14.png" },
            { "2H_Staff_Tier14", "h2_staff_tier14.png" },
            { "2H_Sword_Tier14", "h2_sword_tier14.png" },
            { "1H_Axe_Tier15", "h1_axe_tier15.png" },
            { "1H_Dagger_Tier15", "h1_dagger_tier15.png" },
            { "1H_Hammer_Tier15", "h1_Hammer_tier15.png" },
            { "1H_OffHand_Tier15", "h1_offhand_tier15.png" },
            { "1h_pistol_tier15", "h1_pistol_tier15.png" },
            { "1H_Sword_Tier15", "h1_sword_tier15.png" },
            { "2H_Axe_Tier15", "h2_axe_tier15.png" },
            { "2H_Bow_Tier15", "h2_bow_tier15.png" },
            { "2H_Hammer_Tier15", "h2_hammer_tier15.png" },
            { "2H_Staff_Tier15", "h2_staff_tier15.png" },
            { "2H_Sword_Tier15", "h2_sword_tier15.png" },
            { "1H_Axe_Tier16", "h1_axe_tier16.png" },
            { "1H_Dagger_Tier16", "h1_dagger_tier16.png" },
            { "1H_Hammer_Tier16", "h1_Hammer_tier16.png" },
            { "1H_OffHand_Tier16", "h1_offhand_tier16.png" },
            { "1h_pistol_tier16", "h1_pistol_tier16.png" },
            { "1H_Sword_Tier16", "h1_sword_tier16.png" },
            { "2H_Axe_Tier16", "h2_axe_tier16.png" },
            { "2H_Bow_Tier16", "h2_bow_tier16.png" },
            { "2H_Hammer_Tier16", "h2_hammer_tier16.png" },
            { "2H_Staff_Tier16", "h2_staff_tier16.png" },
            { "2H_Sword_Tier16", "h2_sword_tier16.png" },
            { "1H_Axe_Tier17", "h1_axe_tier17.png" },
            { "1H_Dagger_Tier17", "h1_dagger_tier17.png" },
            { "1H_Hammer_Tier17", "h1_Hammer_tier17.png" },
            { "1H_OffHand_Tier17", "h1_offhand_tier17.png" },
            { "1h_pistol_tier17", "h1_pistol_tier17.png" },
            { "1H_Sword_Tier17", "h1_sword_tier17.png" },
            { "2H_Axe_Tier17", "h2_axe_tier17.png" },
            { "2H_Bow_Tier17", "h2_bow_tier17.png" },
            { "2H_Hammer_Tier17", "h2_hammer_tier17.png" },
            { "2H_Staff_Tier17", "h2_staff_tier17.png" },
            { "2H_Sword_Tier17", "h2_sword_tier17.png" },
            { "1H_Axe_Tier18", "h1_axe_tier18.png" },
            { "1H_Dagger_Tier18", "h1_dagger_tier18.png" },
            { "1H_Hammer_Tier18", "h1_Hammer_tier18.png" },
            { "1H_OffHand_Tier18", "h1_offhand_tier18.png" },
            { "1h_pistol_tier18", "h1_pistol_tier18.png" },
            { "1H_Sword_Tier18", "h1_sword_tier18.png" },
            { "2H_Axe_Tier18", "h2_axe_tier18.png" },
            { "2H_Bow_Tier18", "h2_bow_tier18.png" },
            { "2H_Hammer_Tier18", "h2_hammer_tier18.png" },
            { "2H_Staff_Tier18", "h2_staff_tier18.png" },
            { "2H_Sword_Tier18", "h2_sword_tier18.png" },
            { "2H_Staff_Tier3_Reward", "h2_staff_tier3.png" },
            { "2H_Bow_Tier3_Reward", "h2_bow_tier3.png" },
            { "1h_pistol_tier3_Reward", "h1_pistol_tier3.png" },
            { "1H_Sword_Tier3_Reward", "h1_sword_tier3.png" },
            { "2H_Sword_Tier3_Reward", "h2_sword_tier3.png" },
            { "unique_flintlock_gun_max", "h1_pistol_FlintLockPistol.png" },
            { "Unique_shadow_catalyst_max", "h1_offhand_tier8.png" },
            { "unique_dominion_staff_max", "unique_staff_cryptic.png" },
            { "unique_driftwood_bow_max", "unique_bow_islandsurvivor.png" },
            { "Unique_delivrance_axe_max", "2h_axe_reactorscythe.png" },
            { "unique_driftwood_bow_max_max", "unique_bow_islandsurvivor.png" },
            { "Unique_delivrance_axe_max_max", "2h_axe_reactorscythe.png" },
            { "unique_shield_sacred_max_max", "h1_shield_quintet_of_sundowns.png" },
            { "unique_shield_thing_max_max", "1h_shield_the_thing.png" },
            { "unique_shield_shadow_max_max", "1h_shield_in_tenebris_gloriam.png" },
            { "Unique_bow_projectile_max_max", "bow_2h_templar.png" },
            { "Unique_fire_Sword_max_max", "Doomslayer.png" },
            { "Unique_stasis_staff_max_max", "lantern_staff.png" },
            { "Unique_rend_dagger_max_max", "corrupted_dagger.png" },
            { "Unique_2h_axe_max_max", "h2_axe_orc.png" },
            { "Unique_poison_dagger_max_max", "1h_dagger_senates_imperatum.png" },
            { "Unique_lightning_staff_max_max", "h2_staff_zapstick.png" },
            { "Unique_stone_sword_max_max", "2h_sword_rigards_hope.png" },
            { "Unique_vanity_Sword_max_max", "h1_sword_vanitys_edge.png" },
            { "Unique_envy_Sword_max_max", "h1_sword_blade_of_envy.png" },
            { "unique_cc_mace_max_max", "h1_hammer_orc.png" },
            { "Unique_1h_axe_max_max", "1h_axe_the_apex.png" },
            { "Unique_lightning_sword_max_max", "2h_sword_zephyron_herald_of_change.png" },
            { "Unique_gun_pierce_max_max", "1h_pistol_grahams_shipkiller.png" },
            { "Unique_purifier_catalyst_max_max", "1h_purifier_catalyst.png" },
            { "unique_mace_sleeper_max_max", "h2_hammer_hand_of_the_sleeper.png" },
            { "unique_flintlock_gun_max_max", "h1_pistol_FlintLockPistol.png" },
            { "Unique_shadow_catalyst_max_max", "h1_offhand_tier8.png" },
            { "unique_dominion_staff_max_max", "unique_staff_cryptic.png" },
            { "Unique_purifier_catalyst_max", "1h_purifier_catalyst.png" },
            { "unique_spellblade_catalyst_max", "h1_offhand_spellbladecatalyst.png" },
            { "unique_spellblade_catalyst_max_max", "h1_offhand_spellbladecatalyst.png" },

            // Dev stuff
            { "1h_dagger", "Barbarian_Dagger.png" },
            { "1h_axe", "Barbarian_axe.png" },
            { "2h_axe", "Barbarian_Big_Axe.png" },
            { "1h_sword", "Barbarian_Sword.png" },
            { "2h_sword", "Barbarian_Greatsword.png" },
            { "1h_hammer", "Barbarian_Hammer_shot_01.png" },
            { "2h_hammer", "Barbarian_Warhammer_shot_01.png" },
            { "2h_staff_fire", "barbarian_staff_fire.png" },
            { "2h_staff_frost", "barbarian_staff_ice.png" },
            { "2h_staff_lightning", "barbarian_staff_lightning.png" },
            { "2h_staff_umbra", "barbarian_staff_umbra.png" },
            { "2h_bow", "bow_2h_tier1.png" },
            { "1h_pistol", "gun.png" },
            { "1h_shield", "runique_shield.png" },
            { "1h_trinket", "runique_shield.png" },
            { "Dev_test_sword", "h1_sword_tier1.png" },
            { "Dev_test_bow", "h2_bow_tier1.png" },
            { "1H_Axe_Template", "h1_axe_tier1.png" },
            { "1H_Dagger_Template", "h1_dagger_tier1.png" },
            { "1H_Hammer_Template", "h1_Hammer_tier1.png" },
            { "1H_OffHand_Template", "1h_purifier_catalyst.png" },
            { "1h_pistol_Template", "h1_pistol_tier1.png" },
            { "1H_Sword_Template", "h1_sword_tier1.png" },
            { "2H_Axe_Template", "h2_axe_tier1.png" },
            { "2H_Bow_Template", "h2_bow_tier1.png" },
            { "2H_Hammer_Template", "h2_hammer_tier1.png" },
            { "2H_Staff_Template", "h2_staff_tier1.png" },
            { "2H_Sword_Template", "h2_sword_tier1.png" },
            { "1h_shield_template", "h1_shield_tier1.png" },
        };

        public static readonly Dictionary<string, string> ItemArmor = new Dictionary<string, string>
        {
            { "Heavy_Helmet_Tier1", "Heavy_helmet_tier1.png" },
            { "Heavy_Glove_Tier1", "Heavy_glove_tier1.png" },
            { "Heavy_ChestArmor_Tier1", "Heavy_chestarmor_tier1.png" },
            { "Heavy_Pauldron_Tier1", "Heavy_pauldron_tier1.png" },
            { "Heavy_Pants_Tier1", "Heavy_pants_tier1.png" },
            { "Heavy_Boots_Tier1", "Heavy_boots_tier1.png" },
            { "Heavy_Helmet_Tier2", "Heavy_helmet_tier2.png" },
            { "Heavy_Glove_Tier2", "Heavy_glove_tier2.png" },
            { "Heavy_ChestArmor_Tier2", "Heavy_chestarmor_tier2.png" },
            { "Heavy_ChestArmor_Tier2_Reward", "Heavy_chestarmor_tier2.png" },
            { "Heavy_Pauldron_Tier2", "Heavy_pauldron_tier2.png" },
            { "Heavy_Pants_Tier2", "Heavy_pants_tier2.png" },
            { "Heavy_Boots_Tier2", "Heavy_boots_tier2.png" },
            { "Heavy_Helmet_Tier3", "Heavy_helmet_tier3.png" },
            { "Heavy_Glove_Tier3", "Heavy_glove_tier3.png" },
            { "Heavy_ChestArmor_Tier3", "Heavy_chestarmor_tier3.png" },
            { "Heavy_ChestArmor_Tier3_Reward", "Heavy_chestarmor_tier3.png" },
            { "Heavy_Pauldron_Tier3", "Heavy_pauldron_tier3.png" },
            { "Heavy_Pants_Tier3", "Heavy_pants_tier3.png" },
            { "Heavy_Boots_Tier3", "Heavy_boots_tier3.png" },
            { "Heavy_Helmet_Tier4", "Heavy_helmet_tier4.png" },
            { "Heavy_Helmet_Tier4_Reward", "Heavy_helmet_tier4.png" },
            { "Heavy_Glove_Tier4", "Heavy_glove_tier4.png" },
            { "Heavy_ChestArmor_Tier4", "Heavy_chestarmor_tier4.png" },
            { "Heavy_ChestArmor_Tier4_Reward", "Heavy_chestarmor_tier4.png" },
            { "Heavy_Pauldron_Tier4", "Heavy_pauldron_tier4.png" },
            { "Heavy_Pants_Tier4", "Heavy_pants_tier4.png" },
            { "Heavy_Boots_Tier4", "Heavy_boots_tier4.png" },
            { "Heavy_Helmet_Tier5", "Heavy_helmet_tier5.png" },
            { "Heavy_Helmet_Tier5_Reward", "Heavy_helmet_tier5.png" },
            { "Heavy_Glove_Tier5", "Heavy_glove_tier5.png" },
            { "Heavy_ChestArmor_Tier5", "Heavy_chestarmor_tier5.png" },
            { "Heavy_ChestArmor_Tier5_Reward", "Heavy_chestarmor_tier5.png" },
            { "Heavy_Pauldron_Tier5", "Heavy_pauldron_tier5.png" },
            { "Heavy_Pants_Tier5", "Heavy_pants_tier5.png" },
            { "Heavy_Boots_Tier5", "Heavy_boots_tier5.png" },
            { "Heavy_Helmet_Tier6", "Heavy_helmet_tier6.png" },
            { "Heavy_Glove_Tier6", "Heavy_glove_tier6.png" },
            { "Heavy_ChestArmor_Tier6", "Heavy_chestarmor_tier6.png" },
            { "Heavy_Pauldron_Tier6", "Heavy_pauldron_tier6.png" },
            { "Heavy_Pants_Tier6", "Heavy_pants_tier6.png" },
            { "Heavy_Boots_Tier6", "Heavy_boots_tier6.png" },
            { "Heavy_Helmet_Tier7", "Heavy_helmet_tier7.png" },
            { "Heavy_Glove_Tier7", "Heavy_glove_tier7.png" },
            { "Heavy_ChestArmor_Tier7", "Heavy_chestarmor_tier7.png" },
            { "Heavy_Pauldron_Tier7", "Heavy_pauldron_tier7.png" },
            { "Heavy_Pants_Tier7", "Heavy_pants_tier7.png" },
            { "Heavy_Boots_Tier7", "Heavy_boots_tier7.png" },
            { "Heavy_Helmet_Tier8", "Heavy_helmet_tier8.png" },
            { "Heavy_Glove_Tier8", "Heavy_glove_tier8.png" },
            { "Heavy_ChestArmor_Tier8", "Heavy_chestarmor_tier8.png" },
            { "Heavy_Pauldron_Tier8", "Heavy_pauldron_tier8.png" },
            { "Heavy_Pants_Tier8", "Heavy_pants_tier8.png" },
            { "Heavy_Boots_Tier8", "Heavy_boots_tier8.png" },
            { "Heavy_Helmet_Tier9", "Heavy_helmet_tier9.png" },
            { "Heavy_Glove_Tier9", "Heavy_glove_tier9.png" },
            { "Heavy_ChestArmor_Tier9", "Heavy_chestarmor_tier9.png" },
            { "Heavy_Pauldron_Tier9", "Heavy_pauldron_tier9.png" },
            { "Heavy_Pants_Tier9", "Heavy_pants_tier9.png" },
            { "Heavy_Boots_Tier9", "Heavy_boots_tier9.png" },
            { "Heavy_Helmet_Tier10", "Heavy_helmet_tier10.png" },
            { "Heavy_Glove_Tier10", "Heavy_glove_tier10.png" },
            { "Heavy_ChestArmor_Tier10", "Heavy_chestarmor_tier10.png" },
            { "Heavy_Pauldron_Tier10", "Heavy_pauldron_tier10.png" },
            { "Heavy_Pants_Tier10", "Heavy_pants_tier10.png" },
            { "Heavy_Boots_Tier10", "Heavy_boots_tier10.png" },
            { "Heavy_Helmet_Tier11", "Heavy_helmet_tier11.png" },
            { "Heavy_Glove_Tier11", "Heavy_glove_tier11.png" },
            { "Heavy_ChestArmor_Tier11", "Heavy_chestarmor_tier11.png" },
            { "Heavy_Pauldron_Tier11", "Heavy_pauldron_tier11.png" },
            { "Heavy_Pants_Tier11", "Heavy_pants_tier11.png" },
            { "Heavy_Boots_Tier11", "Heavy_boots_tier11.png" },
            { "Heavy_Helmet_Tier12", "Heavy_helmet_tier12.png" },
            { "Heavy_Glove_Tier12", "Heavy_glove_tier12.png" },
            { "Heavy_ChestArmor_Tier12", "Heavy_chestarmor_tier12.png" },
            { "Heavy_Pauldron_Tier12", "Heavy_pauldron_tier12.png" },
            { "Heavy_Pants_Tier12", "Heavy_pants_tier12.png" },
            { "Heavy_Boots_Tier12", "Heavy_boots_tier12.png" },
            { "Heavy_Helmet_Tier13", "Heavy_helmet_tier13.png" },
            { "Heavy_Glove_Tier13", "Heavy_glove_tier13.png" },
            { "Heavy_ChestArmor_Tier13", "Heavy_chestarmor_tier13.png" },
            { "Heavy_Pauldron_Tier13", "Heavy_pauldron_tier13.png" },
            { "Heavy_Pants_Tier13", "Heavy_pants_tier13.png" },
            { "Heavy_Boots_Tier13", "Heavy_boots_tier13.png" },
            { "Heavy_Helmet_Tier14", "Heavy_helmet_tier14.png" },
            { "Heavy_Glove_Tier14", "Heavy_glove_tier14.png" },
            { "Heavy_ChestArmor_Tier14", "Heavy_chestarmor_tier14.png" },
            { "Heavy_Pauldron_Tier14", "Heavy_pauldron_tier14.png" },
            { "Heavy_Pants_Tier14", "Heavy_pants_tier14.png" },
            { "Heavy_Boots_Tier14", "Heavy_boots_tier14.png" },
            { "Heavy_Helmet_Tier15", "Heavy_helmet_tier15.png" },
            { "Heavy_Glove_Tier15", "Heavy_glove_tier15.png" },
            { "Heavy_ChestArmor_Tier15", "Heavy_chestarmor_tier15.png" },
            { "Heavy_Pauldron_Tier15", "Heavy_pauldron_tier15.png" },
            { "Heavy_Pants_Tier15", "Heavy_pants_tier15.png" },
            { "Heavy_Boots_Tier15", "Heavy_boots_tier15.png" },
            { "Heavy_Helmet_Tier16", "Heavy_helmet_tier16.png" },
            { "Heavy_Glove_Tier16", "Heavy_glove_tier16.png" },
            { "Heavy_ChestArmor_Tier16", "Heavy_chestarmor_tier16.png" },
            { "Heavy_Pauldron_Tier16", "Heavy_pauldron_tier16.png" },
            { "Heavy_Pants_Tier16", "Heavy_pants_tier16.png" },
            { "Heavy_Boots_Tier16", "Heavy_boots_tier16.png" },
            { "Warrior_Helmet_Tier1", "warrior_helmet_tier1.png" },
            { "Warrior_Glove_Tier1", "warrior_glove_tier1.png" },
            { "Warrior_ChestArmor_Tier1", "warrior_chestarmor_tier1.png" },
            { "Warrior_Pauldron_Tier1", "warrior_pauldron_tier1.png" },
            { "Warrior_Pants_Tier1", "warrior_pants_tier1.png" },
            { "Warrior_Boots_Tier1", "warrior_boots_tier1.png" },
            { "Warrior_Helmet_Tier2", "warrior_helmet_tier2.png" },
            { "Warrior_Glove_Tier2", "warrior_glove_tier2.png" },
            { "Warrior_ChestArmor_Tier2", "warrior_chestarmor_tier2.png" },
            { "Warrior_ChestArmor_Tier2_Reward", "warrior_chestarmor_tier2.png" },
            { "Warrior_Pauldron_Tier2", "warrior_pauldron_tier2.png" },
            { "Warrior_Pants_Tier2", "warrior_pants_tier2.png" },
            { "Warrior_Boots_Tier2", "warrior_boots_tier2.png" },
            { "Warrior_Helmet_Tier3", "warrior_helmet_tier3.png" },
            { "Warrior_Glove_Tier3", "warrior_glove_tier3.png" },
            { "Warrior_ChestArmor_Tier3", "warrior_chestarmor_tier3.png" },
            { "Warrior_ChestArmor_Tier3_Reward", "warrior_chestarmor_tier3.png" },
            { "Warrior_Pauldron_Tier3", "warrior_pauldron_tier3.png" },
            { "Warrior_Pants_Tier3", "warrior_pants_tier3.png" },
            { "Warrior_Boots_Tier3", "warrior_boots_tier3.png" },
            { "Warrior_Helmet_Tier4", "warrior_helmet_tier4.png" },
            { "Warrior_Helmet_Tier4_Reward", "warrior_helmet_tier4.png" },
            { "Warrior_Glove_Tier4", "warrior_glove_tier4.png" },
            { "Warrior_ChestArmor_Tier4", "warrior_chestarmor_tier4.png" },
            { "Warrior_ChestArmor_Tier4_Reward", "warrior_chestarmor_tier4.png" },
            { "Warrior_Pauldron_Tier4", "warrior_pauldron_tier4.png" },
            { "Warrior_Pants_Tier4", "warrior_pants_tier4.png" },
            { "Warrior_Boots_Tier4", "warrior_boots_tier4.png" },
            { "Warrior_Helmet_Tier5", "warrior_helmet_tier5.png" },
            { "Warrior_Helmet_Tier5_Reward", "warrior_helmet_tier5.png" },
            { "Warrior_Glove_Tier5", "warrior_glove_tier5.png" },
            { "Warrior_ChestArmor_Tier5", "warrior_chestarmor_tier5.png" },
            { "Warrior_ChestArmor_Tier5_Reward", "warrior_chestarmor_tier5.png" },
            { "Warrior_Pauldron_Tier5", "warrior_pauldron_tier5.png" },
            { "Warrior_Pants_Tier5", "warrior_pants_tier5.png" },
            { "Warrior_Boots_Tier5", "warrior_boots_tier5.png" },
            { "Warrior_Helmet_Tier6", "warrior_helmet_tier6.png" },
            { "Warrior_Glove_Tier6", "warrior_glove_tier6.png" },
            { "Warrior_ChestArmor_Tier6", "warrior_chestarmor_tier6.png" },
            { "Warrior_Pauldron_Tier6", "warrior_pauldron_tier6.png" },
            { "Warrior_Pants_Tier6", "warrior_pants_tier6.png" },
            { "Warrior_Boots_Tier6", "warrior_boots_tier6.png" },
            { "Warrior_Helmet_Tier7", "warrior_helmet_tier7.png" },
            { "Warrior_Glove_Tier7", "warrior_glove_tier7.png" },
            { "Warrior_ChestArmor_Tier7", "warrior_chestarmor_tier7.png" },
            { "Warrior_Pauldron_Tier7", "warrior_pauldron_tier7.png" },
            { "Warrior_Pants_Tier7", "warrior_pants_tier7.png" },
            { "Warrior_Boots_Tier7", "warrior_boots_tier7.png" },
            { "Warrior_Helmet_Tier8", "warrior_helmet_tier8.png" },
            { "Warrior_Glove_Tier8", "warrior_glove_tier8.png" },
            { "Warrior_ChestArmor_Tier8", "warrior_chestarmor_tier8.png" },
            { "Warrior_Pauldron_Tier8", "warrior_pauldron_tier8.png" },
            { "Warrior_Pants_Tier8", "warrior_pants_tier8.png" },
            { "Warrior_Boots_Tier8", "warrior_boots_tier8.png" },
            { "Warrior_Helmet_Tier9", "warrior_helmet_tier9.png" },
            { "Warrior_Glove_Tier9", "warrior_glove_tier9.png" },
            { "Warrior_ChestArmor_Tier9", "warrior_chestarmor_tier9.png" },
            { "Warrior_Pauldron_Tier9", "warrior_pauldron_tier9.png" },
            { "Warrior_Pants_Tier9", "warrior_pants_tier9.png" },
            { "Warrior_Boots_Tier9", "warrior_boots_tier9.png" },
            { "Warrior_Helmet_Tier10", "warrior_helmet_tier10.png" },
            { "Warrior_Glove_Tier10", "warrior_glove_tier10.png" },
            { "Warrior_ChestArmor_Tier10", "warrior_chestarmor_tier10.png" },
            { "Warrior_Pauldron_Tier10", "warrior_pauldron_tier10.png" },
            { "Warrior_Pants_Tier10", "warrior_pants_tier10.png" },
            { "Warrior_Boots_Tier10", "warrior_boots_tier10.png" },
            { "Warrior_Helmet_Tier11", "warrior_helmet_tier11.png" },
            { "Warrior_Glove_Tier11", "warrior_glove_tier11.png" },
            { "Warrior_ChestArmor_Tier11", "warrior_chestarmor_tier11.png" },
            { "Warrior_Pauldron_Tier11", "warrior_pauldron_tier11.png" },
            { "Warrior_Pants_Tier11", "warrior_pants_tier11.png" },
            { "Warrior_Boots_Tier11", "warrior_boots_tier11.png" },
            { "Warrior_Helmet_Tier12", "warrior_helmet_tier12.png" },
            { "Warrior_Glove_Tier12", "warrior_glove_tier12.png" },
            { "Warrior_ChestArmor_Tier12", "warrior_chestarmor_tier12.png" },
            { "Warrior_Pauldron_Tier12", "warrior_pauldron_tier12.png" },
            { "Warrior_Pants_Tier12", "warrior_pants_tier12.png" },
            { "Warrior_Boots_Tier12", "warrior_boots_tier12.png" },
            { "Warrior_Helmet_Tier13", "warrior_helmet_tier13.png" },
            { "Warrior_ChestArmor_Tier13", "warrior_chestarmor_tier13.png" },
            { "Warrior_Pauldron_Tier13", "warrior_pauldron_tier13.png" },
            { "Warrior_Pants_Tier13", "warrior_pants_tier13.png" },
            { "Warrior_Boots_Tier13", "warrior_boots_tier13.png" },
            { "Warrior_Helmet_Tier14", "warrior_helmet_tier14.png" },
            { "Warrior_Glove_Tier14", "warrior_glove_tier14.png" },
            { "Warrior_ChestArmor_Tier14", "warrior_chestarmor_tier14.png" },
            { "Warrior_Pauldron_Tier14", "warrior_pauldron_tier14.png" },
            { "Warrior_Pants_Tier14", "warrior_pants_tier14.png" },
            { "Warrior_Boots_Tier14", "warrior_boots_tier14.png" },
            { "Warrior_Helmet_Tier15", "warrior_helmet_tier15.png" },
            { "Warrior_Glove_Tier15", "warrior_glove_tier15.png" },
            { "Warrior_ChestArmor_Tier15", "warrior_chestarmor_tier15.png" },
            { "Warrior_Pauldron_Tier15", "warrior_pauldron_tier15.png" },
            { "Warrior_Pants_Tier15", "warrior_pants_tier15.png" },
            { "Warrior_Boots_Tier15", "warrior_boots_tier15.png" },
            { "Warrior_Helmet_Tier16", "warrior_helmet_tier16.png" },
            { "Warrior_Glove_Tier13", "warrior_glove_tier16.png" },
            { "Warrior_Glove_Tier16", "warrior_glove_tier16.png" },
            { "Warrior_ChestArmor_Tier16", "warrior_chestarmor_tier16.png" },
            { "Warrior_Pauldron_Tier16", "warrior_pauldron_tier16.png" },
            { "Warrior_Pants_Tier16", "warrior_pants_tier16.png" },
            { "Warrior_Boots_Tier16", "warrior_boots_tier16.png" },
            { "Rogue_Helmet_Tier1", "rogue_helmet_tier1.png" },
            { "Rogue_Glove_Tier1", "rogue_glove_tier1.png" },
            { "Rogue_ChestArmor_Tier1", "rogue_chestarmor_tier1.png" },
            { "Rogue_Pauldron_Tier1", "rogue_pauldron_tier1.png" },
            { "Rogue_Pants_Tier1", "rogue_pants_tier1.png" },
            { "Rogue_Boots_Tier1", "rogue_boots_tier1.png" },
            { "Rogue_Helmet_Tier2", "rogue_helmet_tier2.png" },
            { "Rogue_Glove_Tier2", "rogue_glove_tier2.png" },
            { "Rogue_ChestArmor_Tier2", "rogue_chestarmor_tier2.png" },
            { "Rogue_ChestArmor_Tier2_Reward", "rogue_chestarmor_tier2.png" },
            { "Rogue_Pauldron_Tier2", "rogue_pauldron_tier2.png" },
            { "Rogue_Pants_Tier2", "rogue_pants_tier2.png" },
            { "Rogue_Boots_Tier2", "rogue_boots_tier2.png" },
            { "Rogue_Helmet_Tier3", "rogue_helmet_tier3.png" },
            { "Rogue_Glove_Tier3", "rogue_glove_tier3.png" },
            { "Rogue_ChestArmor_Tier3", "rogue_chestarmor_tier3.png" },
            { "Rogue_ChestArmor_Tier3_Reward", "rogue_chestarmor_tier3.png" },
            { "Rogue_Pauldron_Tier3", "rogue_pauldron_tier3.png" },
            { "Rogue_Pants_Tier3", "rogue_pants_tier3.png" },
            { "Rogue_Boots_Tier3", "rogue_boots_tier3.png" },
            { "Rogue_Helmet_Tier4", "rogue_helmet_tier4.png" },
            { "Rogue_Helmet_Tier4_Reward", "rogue_helmet_tier4.png" },
            { "Rogue_Glove_Tier4", "rogue_glove_tier4.png" },
            { "Rogue_ChestArmor_Tier4", "rogue_chestarmor_tier4.png" },
            { "Rogue_ChestArmor_Tier4_Reward", "rogue_chestarmor_tier4.png" },
            { "Rogue_Pauldron_Tier4", "rogue_pauldron_tier4.png" },
            { "Rogue_Pants_Tier4", "rogue_pants_tier4.png" },
            { "Rogue_Boots_Tier4", "rogue_boots_tier4.png" },
            { "Rogue_Helmet_Tier5", "rogue_helmet_tier5.png" },
            { "Rogue_Helmet_Tier5_Reward", "rogue_helmet_tier5.png" },
            { "Rogue_Glove_Tier5", "rogue_glove_tier5.png" },
            { "Rogue_ChestArmor_Tier5", "rogue_chestarmor_tier5.png" },
            { "Rogue_ChestArmor_Tier5_Reward", "rogue_chestarmor_tier5.png" },
            { "Rogue_Pauldron_Tier5", "rogue_pauldron_tier5.png" },
            { "Rogue_Pants_Tier5", "rogue_pants_tier5.png" },
            { "Rogue_Boots_Tier5", "rogue_boots_tier5.png" },
            { "Rogue_Helmet_Tier6", "rogue_helmet_tier6.png" },
            { "Rogue_Glove_Tier6", "rogue_glove_tier6.png" },
            { "Rogue_ChestArmor_Tier6", "rogue_chestarmor_tier6.png" },
            { "Rogue_Pauldron_Tier6", "rogue_pauldron_tier6.png" },
            { "Rogue_Pants_Tier6", "rogue_pants_tier6.png" },
            { "Rogue_Boots_Tier6", "rogue_boots_tier6.png" },
            { "Rogue_Helmet_Tier7", "rogue_helmet_tier7.png" },
            { "Rogue_Glove_Tier7", "rogue_glove_tier7.png" },
            { "Rogue_ChestArmor_Tier7", "rogue_chestarmor_tier7.png" },
            { "Rogue_Pauldron_Tier7", "rogue_pauldron_tier7.png" },
            { "Rogue_Pants_Tier7", "rogue_pants_tier7.png" },
            { "Rogue_Boots_Tier7", "rogue_boots_tier7.png" },
            { "Rogue_Helmet_Tier8", "rogue_helmet_tier8.png" },
            { "Rogue_Glove_Tier8", "rogue_glove_tier8.png" },
            { "Rogue_ChestArmor_Tier8", "rogue_chestarmor_tier8.png" },
            { "Rogue_Pauldron_Tier8", "rogue_pauldron_tier8.png" },
            { "Rogue_Pants_Tier8", "rogue_pants_tier8.png" },
            { "Rogue_Boots_Tier8", "rogue_boots_tier8.png" },
            { "Rogue_Helmet_Tier9", "rogue_helmet_tier9.png" },
            { "Rogue_Glove_Tier9", "rogue_glove_tier9.png" },
            { "Rogue_ChestArmor_Tier9", "rogue_chestarmor_tier9.png" },
            { "Rogue_Pauldron_Tier9", "rogue_pauldron_tier9.png" },
            { "Rogue_Pants_Tier9", "rogue_pants_tier9.png" },
            { "Rogue_Boots_Tier9", "rogue_boots_tier9.png" },
            { "Rogue_Helmet_Tier10", "rogue_helmet_tier10.png" },
            { "Rogue_Glove_Tier10", "rogue_glove_tier10.png" },
            { "Rogue_ChestArmor_Tier10", "rogue_chestarmor_tier10.png" },
            { "unique_ezaneal_chest_max_max", "rogue_chestarmor_tier10.png" },
            { "Rogue_Pauldron_Tier10", "rogue_pauldron_tier10.png" },
            { "Rogue_Pants_Tier10", "rogue_pants_tier10.png" },
            { "Rogue_Boots_Tier10", "rogue_boots_tier10.png" },
            { "Rogue_Helmet_Tier11", "rogue_helmet_tier11.png" },
            { "Rogue_Glove_Tier11", "rogue_glove_tier11.png" },
            { "Rogue_ChestArmor_Tier11", "rogue_chestarmor_tier11.png" },
            { "Rogue_Pauldron_Tier11", "rogue_pauldron_tier11.png" },
            { "Rogue_Pants_Tier11", "rogue_pants_tier11.png" },
            { "Rogue_Boots_Tier11", "rogue_boots_tier11.png" },
            { "Rogue_Helmet_Tier12", "rogue_helmet_tier12.png" },
            { "Rogue_Glove_Tier12", "rogue_glove_tier12.png" },
            { "Rogue_ChestArmor_Tier12", "rogue_chestarmor_tier12.png" },
            { "Rogue_Pauldron_Tier12", "rogue_pauldron_tier12.png" },
            { "Rogue_Pants_Tier12", "rogue_pants_tier12.png" },
            { "Rogue_Boots_Tier12", "rogue_boots_tier12.png" },
            { "Rogue_Helmet_Tier13", "rogue_helmet_tier13.png" },
            { "Rogue_Glove_Tier13", "rogue_glove_tier13.png" },
            { "Rogue_ChestArmor_Tier13", "rogue_chestarmor_tier13.png" },
            { "Rogue_Pauldron_Tier13", "rogue_pauldron_tier13.png" },
            { "Rogue_Pants_Tier13", "rogue_pants_tier13.png" },
            { "Rogue_Boots_Tier13", "rogue_boots_tier13.png" },
            { "Rogue_Helmet_Tier14", "rogue_helmet_tier14.png" },
            { "Rogue_Glove_Tier14", "rogue_glove_tier14.png" },
            { "Rogue_ChestArmor_Tier14", "rogue_chestarmor_tier14.png" },
            { "Rogue_Pauldron_Tier14", "rogue_pauldron_tier14.png" },
            { "Rogue_Pants_Tier14", "rogue_pants_tier14.png" },
            { "Rogue_Boots_Tier14", "rogue_boots_tier14.png" },
            { "Rogue_Helmet_Tier15", "rogue_helmet_tier15.png" },
            { "Rogue_Glove_Tier15", "rogue_glove_tier15.png" },
            { "Rogue_ChestArmor_Tier15", "rogue_chestarmor_tier15.png" },
            { "Rogue_Pauldron_Tier15", "rogue_pauldron_tier15.png" },
            { "Rogue_Pants_Tier15", "rogue_pants_tier15.png" },
            { "Rogue_Boots_Tier15", "rogue_boots_tier15.png" },
            { "Rogue_Helmet_Tier16", "rogue_helmet_tier16.png" },
            { "Rogue_Glove_Tier16", "rogue_glove_tier16.png" },
            { "Rogue_ChestArmor_Tier16", "rogue_chestarmor_tier16.png" },
            { "Rogue_Pauldron_Tier16", "rogue_pauldron_tier16.png" },
            { "Rogue_Pants_Tier16", "rogue_pants_tier16.png" },
            { "Rogue_Boots_Tier16", "rogue_boots_tier16.png" },
            { "Mage_Helmet_Tier1", "mage_helmet_tier1.png" },
            { "Mage_Glove_Tier1", "mage_glove_tier1.png" },
            { "Mage_ChestArmor_Tier1", "mage_chestarmor_tier1.png" },
            { "Mage_Pauldron_Tier1", "mage_pauldron_tier1.png" },
            { "Mage_Pants_Tier1", "mage_pants_tier1.png" },
            { "Mage_Boots_Tier1", "mage_boots_tier1.png" },
            { "Mage_Helmet_Tier2", "mage_helmet_tier2.png" },
            { "Mage_Glove_Tier2", "mage_glove_tier2.png" },
            { "Mage_ChestArmor_Tier2", "mage_chestarmor_tier2.png" },
            { "Mage_ChestArmor_Tier2_Reward", "mage_chestarmor_tier2.png" },
            { "Mage_Pauldron_Tier2", "mage_pauldron_tier2.png" },
            { "Mage_Pants_Tier2", "mage_pants_tier2.png" },
            { "Mage_Boots_Tier2", "mage_boots_tier2.png" },
            { "Mage_Helmet_Tier3", "mage_helmet_tier3.png" },
            { "Mage_Glove_Tier3", "mage_glove_tier3.png" },
            { "Mage_ChestArmor_Tier3", "mage_chestarmor_tier3.png" },
            { "Mage_ChestArmor_Tier3_Reward", "mage_chestarmor_tier3.png" },
            { "Mage_Pauldron_Tier3", "mage_pauldron_tier3.png" },
            { "Mage_Pants_Tier3", "mage_pants_tier3.png" },
            { "Mage_Boots_Tier3", "mage_boots_tier3.png" },
            { "Mage_Helmet_Tier4", "mage_helmet_tier4.png" },
            { "Mage_Helmet_Tier4_Reward", "mage_helmet_tier4.png" },
            { "Mage_Glove_Tier4", "mage_glove_tier4.png" },
            { "Mage_ChestArmor_Tier4", "mage_chestarmor_tier4.png" },
            { "Mage_ChestArmor_Tier4_Reward", "mage_chestarmor_tier4.png" },
            { "Mage_Pauldron_Tier4", "mage_pauldron_tier4.png" },
            { "Mage_Pants_Tier4", "mage_pants_tier4.png" },
            { "Mage_Boots_Tier4", "mage_boots_tier4.png" },
            { "Mage_Helmet_Tier5", "mage_helmet_tier5.png" },
            { "Mage_Helmet_Tier5_Reward", "mage_helmet_tier5.png" },
            { "Mage_Glove_Tier5", "mage_glove_tier5.png" },
            { "Mage_ChestArmor_Tier5", "mage_chestarmor_tier5.png" },
            { "Mage_ChestArmor_Tier5_Reward", "mage_chestarmor_tier5.png" },
            { "Mage_Pauldron_Tier5", "mage_pauldron_tier5.png" },
            { "Mage_Pants_Tier5", "mage_pants_tier5.png" },
            { "Mage_Boots_Tier5", "mage_boots_tier5.png" },
            { "Mage_Helmet_Tier6", "mage_helmet_tier6.png" },
            { "Mage_Glove_Tier6", "mage_glove_tier6.png" },
            { "Mage_ChestArmor_Tier6", "mage_chestarmor_tier6.png" },
            { "Mage_Pauldron_Tier6", "mage_pauldron_tier6.png" },
            { "Mage_Pants_Tier6", "mage_pants_tier6.png" },
            { "Mage_Boots_Tier6", "mage_boots_tier6.png" },
            { "Mage_Helmet_Tier7", "mage_helmet_tier7.png" },
            { "Mage_Glove_Tier7", "mage_glove_tier7.png" },
            { "Mage_ChestArmor_Tier7", "mage_chestarmor_tier7.png" },
            { "Mage_Pauldron_Tier7", "mage_pauldron_tier7.png" },
            { "Mage_Pants_Tier7", "mage_pants_tier7.png" },
            { "Mage_Boots_Tier7", "mage_boots_tier7.png" },
            { "Mage_Helmet_Tier8", "mage_helmet_tier8.png" },
            { "Mage_Glove_Tier8", "mage_glove_tier8.png" },
            { "Mage_ChestArmor_Tier8", "mage_chestarmor_tier8.png" },
            { "Mage_Pauldron_Tier8", "mage_pauldron_tier8.png" },
            { "Mage_Pants_Tier8", "mage_pants_tier8.png" },
            { "Mage_Boots_Tier8", "mage_boots_tier8.png" },
            { "Mage_Helmet_Tier9", "mage_helmet_tier9.png" },
            { "Mage_Glove_Tier9", "mage_glove_tier9.png" },
            { "Mage_ChestArmor_Tier9", "mage_chestarmor_tier9.png" },
            { "Mage_Pauldron_Tier9", "mage_pauldron_tier9.png" },
            { "Mage_Pants_Tier9", "mage_pants_tier9.png" },
            { "Mage_Boots_Tier9", "mage_boots_tier9.png" },
            { "Mage_Helmet_Tier10", "mage_helmet_tier10.png" },
            { "Mage_Glove_Tier10", "mage_glove_tier10.png" },
            { "Mage_ChestArmor_Tier10", "mage_chestarmor_tier10.png" },
            { "Mage_Pauldron_Tier10", "mage_pauldron_tier10.png" },
            { "Mage_Pants_Tier10", "mage_pants_tier10.png" },
            { "Mage_Boots_Tier10", "mage_boots_tier10.png" },
            { "Mage_Helmet_Tier11", "mage_helmet_tier11.png" },
            { "Mage_Glove_Tier11", "mage_glove_tier11.png" },
            { "Mage_ChestArmor_Tier11", "mage_chestarmor_tier11.png" },
            { "Mage_Pauldron_Tier11", "mage_pauldron_tier11.png" },
            { "Mage_Pants_Tier11", "mage_pants_tier11.png" },
            { "Mage_Boots_Tier11", "mage_boots_tier11.png" },
            { "Mage_Helmet_Tier12", "mage_helmet_tier12.png" },
            { "Mage_Glove_Tier12", "mage_glove_tier12.png" },
            { "Mage_ChestArmor_Tier12", "mage_chestarmor_tier12.png" },
            { "Mage_Pauldron_Tier12", "mage_pauldron_tier12.png" },
            { "Mage_Pants_Tier12", "mage_pants_tier12.png" },
            { "Mage_Boots_Tier12", "mage_boots_tier12.png" },
            { "Mage_Helmet_Tier13", "mage_helmet_tier13.png" },
            { "Mage_Glove_Tier13", "mage_glove_tier13.png" },
            { "Mage_ChestArmor_Tier13", "mage_chestarmor_tier13.png" },
            { "Mage_Pauldron_Tier13", "mage_pauldron_tier13.png" },
            { "Mage_Pants_Tier13", "mage_pants_tier13.png" },
            { "Mage_Boots_Tier13", "mage_boots_tier13.png" },
            { "Mage_Helmet_Tier14", "mage_helmet_tier14.png" },
            { "Mage_Glove_Tier14", "mage_glove_tier14.png" },
            { "Mage_ChestArmor_Tier14", "mage_chestarmor_tier14.png" },
            { "Mage_Pauldron_Tier14", "mage_pauldron_tier14.png" },
            { "Mage_Pants_Tier14", "mage_pants_tier14.png" },
            { "Mage_Boots_Tier14", "mage_boots_tier14.png" },
            { "Mage_Helmet_Tier15", "mage_helmet_tier15.png" },
            { "Mage_Glove_Tier15", "mage_glove_tier15.png" },
            { "Mage_ChestArmor_Tier15", "mage_chestarmor_tier15.png" },
            { "Mage_Pauldron_Tier15", "mage_pauldron_tier15.png" },
            { "Mage_Pants_Tier15", "mage_pants_tier15.png" },
            { "Mage_Boots_Tier15", "mage_boots_tier15.png" },
            { "Mage_Helmet_Tier16", "mage_helmet_tier16.png" },
            { "Mage_Glove_Tier16", "mage_glove_tier16.png" },
            { "Mage_ChestArmor_Tier16", "mage_chestarmor_tier16.png" },
            { "Mage_Pauldron_Tier16", "mage_pauldron_tier16.png" },
            { "Mage_Pants_Tier16", "mage_pants_tier16.png" },
            { "Mage_Boots_Tier16", "mage_boots_tier16.png" },
            { "unique_pants_abyssal", "unique_pants_abyssal_echo.png" },
            { "unique_pants_abyssal_max", "unique_pants_abyssal_echo.png" },
            { "unique_pants_abyssal_max_max", "unique_pants_abyssal_echo.png" },
            { "unique_chest_agony", "unique_chestarmor_agony.png" },
            { "unique_chest_agony_max", "unique_chestarmor_agony.png" },
            { "unique_chest_agony_max_max", "unique_chestarmor_agony.png" },
            { "unique_glove_firstmen", "unique_glove_bracer_of_the_first_men.png" },
            { "unique_glove_firstmen_max", "unique_glove_bracer_of_the_first_men.png" },
            { "unique_glove_firstmen_max_max", "unique_glove_bracer_of_the_first_men.png" },
            { "unique_should_envoywar", "unique_pauldron_envoywar.png" },
            { "unique_should_envoywar_max", "unique_pauldron_envoywar.png" },
            { "unique_should_envoywar_max_max", "unique_pauldron_envoywar.png" },
            { "Prisoner_Armband", "unique_glove_prisoner.png" },
            { "Prisoner_Chest", "unique_chestarmor_prisoner.png" },
            { "Prisoner_Pants", "unique_pants_prisoner.png" },
            { "Prisoner_Boots", "unique_boots_prisoner.png" },
            { "unique_torso_searingsong", "unique_chestarmor_searingsong.png" },
            { "unique_torso_searingsong_max", "unique_chestarmor_searingsong.png" },
            { "unique_torso_searingsong_max_max", "unique_chestarmor_searingsong.png" },
            { "KickStarter01_Helmet", "unique_helmet_kickstarter_1.png" },
            { "KickStarter01_Armband", "unique_glove_kickstarter_1.png" },
            { "KickStarter01_Chest", "unique_chestarmor_kickstarter_1.png" },
            { "KickStarter01_Pants", "unique_pants_kickstarter_1.png" },
            { "KickStarter01_Boots", "unique_boots_kickstarter_1.png" },
            { "KickStarter02_Helmet", "unique_helmet_kickstarter_2.png" },
            { "KickStarter02_Armband", "unique_glove_kickstarter_2.png" },
            { "KickStarter02_Chest", "unique_chestarmor_kickstarter_2.png" },
            { "KickStarter02_Pants", "unique_pants_kickstarter_2.png" },
            { "KickStarter02_Boots", "unique_boots_kickstarter_2.png" },
            { "KickStarter03_Helmet", "unique_helmet_kickstarter_3.png" },
            { "KickStarter03_Armband", "unique_glove_kickstarter_3.png" },
            { "KickStarter03_Chest", "unique_chestarmor_kickstarter_3.png" },
            { "KickStarter03_Pants", "unique_pants_kickstarter_3.png" },
            { "KickStarter03_Boots", "unique_boots_kickstarter_3.png" },
            { "Energizer_Chest", "unique_chestarmor_energizer.png" },
            { "unique_ezaneal_chest_max", "unique_chestarmor_energizer.png" },
            { "unique_frostweave_chest_max", "unique_Sharpicechest_armor.png" },
            { "unique_frostweave_chest_max_max", "unique_Sharpicechest_armor.png" },
            { "unique_figurehead_pants_max", "unique_nododgepants.png" },
            { "unique_figurehead_pants_max_max", "unique_nododgepants.png" },
            { "unique_necromancer_shoulder_max", "unique_summon_shoulder.png" },
            { "unique_necromancer_shoulder_max_max", "unique_summon_shoulder.png" },
            { "unique_champion_helmet_max", "unique_lastchampionhelmet.png" },
            { "unique_champion_helmet_max_max", "unique_lastchampionhelmet.png" },
            { "unique_expurgation_glove_max", "unique_exorcistbracer.png" },
            { "unique_expurgation_glove_max_max", "unique_exorcistbracer.png" },
            { "unique_republic_helmet_max", "unique_helmet_RepuSniper.png" },
            { "unique_republic_helmet_max_max", "unique_helmet_RepuSniper.png" }
        };
    }
}
